<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="mass" value="1.5"/>
  <xacro:property name="radius" value="0.35"/>
  <xacro:property name="length" value="1.9"/>

  <xacro:macro name="ground_station_antenna" params="name antenna_height">
    <link name="${name}_link">
      <inertial>
        <mass value="1.0" />
        <inertia 
          ixx="${1/12*mass*(3*radius*radius + length*length)}" 
          ixy="0" 
          ixz="0" 
          iyy="${1/12*mass*(3*radius*radius + length*length)}" 
          iyz="0" 
          izz="${1/2*mass*radius*radius}"
        />
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="https://fuel.gazebosim.org/1.0/OpenRobotics/models/antenna%20/5/files/meshes/antenna.dae"/>
        </geometry>
        <origin xyz="0 0 -${antenna_height}" rpy="0 0 ${3*pi/4}"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <origin xyz="0 0 ${-antenna_height/2}" rpy="0 0 0"/>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="gazebo" params="name">
    <gazebo>
      <static>true</static>
      <plugin
        filename="ignition-gazebo-comms-endpoint-system"
        name="ignition::gazebo::systems::CommsEndpoint">
        <address>${name}</address>
        <topic>${name}/rx</topic>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>